name: 2020 testing

on:
  push:
    branches: '*'
    paths: '2020/**'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: perldocker/perl-tester:5.28

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: cpanm --installdeps --notest .
        working-directory: 2020

      - name: Run tests
        run: prove -lv
        working-directory: 2020
