name: 2020 testing

on:
  push:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: perldocker/perl-tester:5.28

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        working-directory: ./2020
        run: cpanm --installdeps --notest .

      - name: Run tests
        working-directory: ./2020
        run: prove -lv
