name: 2020 testing

on:
  push:
    branches:
      - master
    paths:
      - '2020/**'

jobs:
  perl:
    runs-on: ubuntu-latest
    container:
      image: perldocker/perl-tester:5.28
    steps:
      - uses: actions/checkout@v2
      - run: cpanm --installdeps .
        working-directory: 2020
      - run: prove -lv t
        working-directory: 2020
